name: "Update DMC races"
on:
  schedule:
    - cron: "0 1 * * *" # every monday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Make Request
      uses: fjogeleit/http-request-action@v2
      with:
        method: 'GET'
        url: "https://api.rc-cloud.de/update-dmc"
        timeout: 30000
